"Piece" class added
SquadroCorp/squadrosu pull request #1
Opened 2021-12-25 17:18 UTC by Abdou78130

2021-12-25 17:29 UTC, Speykious requested changes
Ça a l'air bien, mais pour les settings vscode ça se fait pas dans le projet :p

2021-12-25 17:29 UTC, Speykious commented on .vscode/settings.json
> +}
Ça faut le mettre dans tes settings personnelles, pas dans celles du projet

2021-12-25 17:29 UTC, Speykious commented on Squadrosu.Framework/Board.cs
> +    public bool Move(Piece piece, Player player)
Pour "incohérences" tu parlais du type de `piece` j'imagine ? Dans ce cas c'est parfait, aucun problème :)

2021-12-25 17:29 UTC, Speykious commented on Squadrosu.Framework/Piece.cs
> +    /// To which player is the current piece.
Ce serait plutôt `/// Which player owns this piece.`

2021-12-25 17:29 UTC, Speykious commented on Squadrosu.Framework/GameAction.cs
> -    // TODO: think about the type of the piece parameter
Du coup vu qu'on part sur une classe `Piece` je pense qu'on peut enlever ce todo

2021-12-25 17:29 UTC, Speykious commented on Squadrosu.Framework/Piece.cs
> +
Lignes vides >_< Mais j'imagine que t'as ensuite envie d'ajouter des méthodes et aussi un constructeur, donc bon x')

2021-12-25 17:40 UTC, Abdou78130 commented on .vscode/settings.json
> +}
C'est pas moi qui l'ai fait XD

2021-12-25 17:40 UTC, Abdou78130 commented on Squadrosu.Framework/Board.cs
> +    public bool Move(Piece piece, Player player)
Yep cest bien ça

2021-12-25 17:42 UTC, Abdou78130 commented on Squadrosu.Framework/Piece.cs
> +    /// To which player is the current piece.
Désolé de mon anglais approximatif XD

2021-12-25 18:10 UTC, Speykious commented
Je sais pas ce qui s'est passé mais il y a bien plus de changements qu'il ne devrait y en avoir... 7_7

2021-12-25 19:55 UTC, Speykious requested changes
Dis-moi si tu as du mal avec le concept de propriétés en C# x')

2021-12-25 19:55 UTC, Speykious commented on Squadrosu.Framework/Piece.cs
> +    private int Position { get; set; }
Quand j'y pense, pourquoi les propriétés sont `private` ? Je m'imaginais qu'on voudrait pouvoir par exemple obtenir la position de la pièce sans pouvoir la modifier directement, ce qui ferait donc `public int Position { get; private set; }`...

Par contre si tu veux vraiment mettre ça en `private` il faut l'écrire en lowerCamelCase, donc ici `position` (et pareil pour les autres).

2021-12-29 18:55 UTC, Speykious requested changes
C'est une bonne structure de donnée mais faut *vraiment pas* négliger les tests, surtout les `Assert`.
D'ailleurs, comme en Java, la plupart du temps tu m'as pas besoin de mettre des `this.`.

2021-12-29 18:55 UTC, Speykious commented on Squadrosu.Framework.Test/TestBoard.cs
> +        TestContext.Progress.WriteLine(board);
La plupart du code ici n'est pas à propos de l'initialisation du `Board`. Tout ce qui est en dehors de `var board = new Board();` doit être dans un autre test avec un nom qui fait sens.
Et évidemment tu as complètement négligé les `Assert`, du coup les tests sont très peu utiles même avec l'affichage -_-

2021-12-29 18:55 UTC, Speykious commented on Squadrosu.Framework/Board.cs
> +    public Piece?[,] Positions { get; private set; } = new Piece[7, 7];
Je suggère un truc plus descriptif
```suggestion
    /// <summary>
    /// Grid where pieces are placed and moved
    /// </summary>
    public Piece?[,] Positions { get; private set; } = new Piece[7, 7];
```
D'ailleurs c'est une bonne idée d'avoir fait une grille

2021-12-29 18:55 UTC, Speykious commented on Squadrosu.Framework/Board.cs
> +    public Piece[] Black { get; private set; } = new Piece[5];
Tu peux mettre ces deux propriétés en `readonly`, vu que les tableaux (et non pas les pièces) ne seront jamais réaffectés
```suggestion
    /// <summary>
    /// List of White Pieces
    /// </summary>
    public readonly Piece[] White = new Piece[5];

    /// <summary>
    /// List of Black Pieces
    /// </summary>
    public readonly Piece[] Black = new Piece[5];
```

2021-12-29 18:55 UTC, Speykious commented on Squadrosu.Framework/Board.cs
> +            Positions[i + 1, 0] = Black[i];
Je pense que c'est mieux de créer les `Piece`s dans le constructeur, puis de seulement changer leur position dans `Reset`, vu qu'elles sont toutes déjà placées sur leur `LineNumber` qui est correct.

2021-12-29 18:55 UTC, Speykious commented on Squadrosu.Framework/Piece.cs
> +    }
Je m'attendais pas à ça, mais je vois en quoi c'est utile...
Mais pour le coup je pense que ça devrait être une autre fonction.
```suggestion
    public void PlaceOnEdge()
    {
        Position = Direction == Direction.Forward ? 0 : 6;
    }

    public void Reset()
    {
        Direction = Direction.Forward;
        PlaceOnEdge();
    }
```

2021-12-29 18:55 UTC, Speykious commented on Squadrosu.Framework/Piece.cs
> +    }
Heureux de savoir que ma fonction marche sans problème :D

2021-12-29 18:55 UTC, Speykious commented on Squadrosu.Framework/Piece.cs
> +            }
Houlà le double `if` nest 7_7
```suggestion
            if (isBlack && board.Positions[LineNumber, i + 1] != null)
            {
                while (board.Positions[LineNumber, i + 1] != null)
                {
                    board.Positions[LineNumber, i + 1].Reset();
                    newPosition = i + 2;
                    i++;
                }
                i = 7;
            }
            else if (board.Positions[i + 1, LineNumber] != null)
            {
                while (board.Positions[i + 1, LineNumber] != null)
                {
                    board.Positions[i + 1, LineNumber].Reset();
                    newPosition = i + 2;
                    i++;
                }
                i = 7;
            }
```

2021-12-29 18:55 UTC, Speykious commented on Squadrosu.Framework/Piece.cs
> +    private void moveForward(Board board)
Je pense que tu pourrais raisonnablement faire de ce `Board` une propriété de `Piece`

2021-12-29 18:55 UTC, Speykious commented on Squadrosu.Framework/Piece.cs
> +            }
Même chose ici, il y a un double nest de `if` et tu peux raccourcir ce `else` en `else if`

2021-12-29 18:55 UTC, Speykious commented on Squadrosu.Framework/Board.cs
> +        int cptw = 0, cptb = 0;
*Eh*, c'est un peu court comme nom. `finishedWhites` et `finishedBlacks` peut-être ?
Bof, pas très important de toute façon haha

2021-12-29 18:59 UTC, Abdou78130 commented on Squadrosu.Framework.Test/TestBoard.cs
> +        TestContext.Progress.WriteLine(board);
Si si je t'assure que j'avais fait tout les assert mais a la fin je les ai retiré après que tout ait fonctionné (je sais pas pk d'ailleurs).

2021-12-29 18:59 UTC, Abdou78130 commented on Squadrosu.Framework/Board.cs
> +    public Piece[] Black { get; private set; } = new Piece[5];
J'ai essayé mais ça me mettait une erreur

2021-12-29 19:00 UTC, Speykious commented on Squadrosu.Framework.Test/TestBoard.cs
> +        TestContext.Progress.WriteLine(board);
MDRRRRRRR

2021-12-29 19:01 UTC, Speykious commented on Squadrosu.Framework/Board.cs
> +    public Piece[] Black { get; private set; } = new Piece[5];
On verra ça en Live Share

2021-12-29 19:06 UTC, Abdou78130 commented on Squadrosu.Framework/Board.cs
> +            Positions[i + 1, 0] = Black[i];
C'est fait.

2021-12-29 19:08 UTC, Speykious commented on Squadrosu.Framework/Board.cs
> +            Positions[i + 1, 0] = Black[i];
Dans un nouveau commit ?

2021-12-29 19:09 UTC, Abdou78130 commented on Squadrosu.Framework/Piece.cs
> +    }
C'est bon

2021-12-29 19:10 UTC, Abdou78130 commented on Squadrosu.Framework/Piece.cs
> +    }
T'avais juste inversé le 1 et 3 au départ XD

2021-12-29 19:11 UTC, Abdou78130 commented on Squadrosu.Framework/Piece.cs
> +            }
Ok

2021-12-29 19:14 UTC, Abdou78130 commented on Squadrosu.Framework/Piece.cs
> +            }
Ok

2021-12-29 19:14 UTC, Speykious reviewed
LGTM (Looks Good To Me)

2021-12-29 19:15 UTC, Abdou78130 commented on Squadrosu.Framework/Board.cs
> +        int cptw = 0, cptb = 0;
ok

2022-01-02 19:34 UTC, Speykious requested changes
Bon bah super, c'est presque prêt :)
Il ne manque plus que des problèmes mineurs de formattage.

2022-01-02 19:34 UTC, Speykious commented on Squadrosu.Framework/Board.cs
> +        int finidhedWhites = 0, finidhedBlacks = 0;
typo xd

2022-01-02 19:34 UTC, Speykious commented on Squadrosu.Framework/Piece.cs
>      }
C'est marrant que je ne le remarque que maintenant, mais les arguments ne sont pas censés être en `PascalCase`, normalement ton éditeur a dû te le dire
```suggestion
    public Piece(Player player, int lineNumber, Board board)
    {
        Direction = Direction.Forward;
        Position = 0;
        LineNumber = lineNumber;
        Player = player;
        Board = board;
    }
```

2022-01-02 19:34 UTC, Speykious commented on Squadrosu.Framework/Piece.cs
> +        this.Board.Update();
Ça sert à rien de mettre un `this` ici, comme un peu partout d'ailleurs. Il est optionnel comme en Java, et on ne le met que quand on peut pas l'enlever

2022-01-11 23:41 UTC, Speykious approved these changes
L'absence totale d'`Assert`s m'énerve, mais c'est pas grave.

2022-01-12 00:02 UTC, merged